# Use a base image with Maven already installed
FROM maven:3.8.3-openjdk-17

# Set the working directory in the builder stage
WORKDIR /app

# Copy the pom.xml file to the container
COPY ./pom.xml ./

# Download dependencies and plugins needed for building
RUN mvn dependency:go-offline

# Copy the rest of the project files to the container
COPY ./src ./src

# Start Tomcat
CMD ["mvn" , "package"]
