# Use a base image with Maven already installed
FROM maven:3.8.3-openjdk-8

# Set the working directory in the builder stage
WORKDIR /app

# Copy the pom.xml file to the container
COPY ./pom.xml ./

# Copy the rest of the project files to the container
COPY ./server ./app/server
COPY ./webapp ./web/webapp

# Download dependencies and plugins needed for building
RUN mvn dependency:go-offline



# Start Tomcat
CMD ["mvn" , "package"]
